apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: aliclusterconfigs.ali.cattle.io
spec:
  group: ali.cattle.io
  names:
    kind: AliClusterConfig
    plural: aliclusterconfigs
    shortNames:
    - alicc
    singular: aliclusterconfig
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              addons:
                items:
                  properties:
                    config:
                      nullable: true
                      type: string
                    name:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              alibabaCredentialSecret:
                nullable: true
                type: string
              clusterId:
                nullable: true
                type: string
              clusterName:
                nullable: true
                type: string
              clusterSpec:
                nullable: true
                type: string
              clusterType:
                nullable: true
                type: string
              containerCidr:
                nullable: true
                type: string
              endpointPublicAccess:
                type: boolean
              imported:
                type: boolean
              isEnterpriseSecurityGroup:
                nullable: true
                type: boolean
              kubernetesVersion:
                nullable: true
                type: string
              nodeCidrMask:
                type: integer
              nodePools:
                items:
                  properties:
                    autoRenew:
                      type: boolean
                    autoRenewPeriod:
                      type: integer
                    dataDisks:
                      items:
                        properties:
                          autoSnapshotPolicyId:
                            nullable: true
                            type: string
                          category:
                            nullable: true
                            type: string
                          encrypted:
                            nullable: true
                            type: string
                          size:
                            type: integer
                        type: object
                      nullable: true
                      type: array
                    desiredSize:
                      nullable: true
                      type: integer
                    enableAutoScaling:
                      nullable: true
                      type: boolean
                    imageId:
                      nullable: true
                      type: string
                    imageType:
                      nullable: true
                      type: string
                    instanceChargeType:
                      nullable: true
                      type: string
                    instanceTypes:
                      items:
                        nullable: true
                        type: string
                      nullable: true
                      type: array
                    keyPair:
                      nullable: true
                      type: string
                    maxInstances:
                      nullable: true
                      type: integer
                    minInstances:
                      nullable: true
                      type: integer
                    name:
                      nullable: true
                      type: string
                    nodePoolId:
                      nullable: true
                      type: string
                    period:
                      type: integer
                    periodUnit:
                      nullable: true
                      type: string
                    runtime:
                      nullable: true
                      type: string
                    runtimeVersion:
                      nullable: true
                      type: string
                    scalingType:
                      nullable: true
                      type: string
                    systemDiskCategory:
                      nullable: true
                      type: string
                    systemDiskSize:
                      type: integer
                    vSwitchIds:
                      items:
                        nullable: true
                        type: string
                      nullable: true
                      type: array
                  type: object
                nullable: true
                type: array
              podVswitchIds:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              proxyMode:
                nullable: true
                type: string
              regionId:
                nullable: true
                type: string
              resourceGroupId:
                nullable: true
                type: string
              securityGroupId:
                nullable: true
                type: string
              serviceCidr:
                nullable: true
                type: string
              snatEntry:
                type: boolean
              vpcId:
                nullable: true
                type: string
              vswitchIds:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              zoneIds:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
            type: object
          status:
            properties:
              failureMessage:
                nullable: true
                type: string
              phase:
                nullable: true
                type: string
              upgradeTaskId:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
